name: Deploy to GitHub Pages from dev

on:
  push:
    branches: [ "dev" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Ajusta según la versión que necesites

      - name: Verificar autenticación SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh -T git@github.com || true

      - name: Install dependencies and build
        run: |
          cd en_assistant
          npm install
          npm run build

      - name: Deploy via SSH
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          publish_dir: en_assistant/dist
          # Asegúrate que ese sea el directorio de salida del build
